name: Bot Lomadee Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Executa a cada 30 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar o bot
        env:
          LOMADEE_API_KEY: ${{ secrets.LOMADEE_API_KEY }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_USERNAME: ${{ secrets.TELEGRAM_CHAT_ID }}
          LOMADEE_SOURCE_ID: ${{ secrets.LOMADEE_SOURCE_ID }}
        run: python lomadee_telegram_bot.py

      - name: Salvar progresso (postados.json)
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add postados.json || exit 0
          git commit -m "Atualiza historico de postados [skip ci]" || exit 0
          git push
